In [7]:
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [3]:
path = 'C:/Users/heath/Desktop/W207/data/'
main_df = pd.read_csv(path+'cleaned_data.csv')

In [11]:
sid = SentimentIntensityAnalyzer()

In [13]:
main_df['sent_scores'] = main_df['body'].apply(lambda body: sid.polarity_scores(body))

In [14]:
main_df

,Unnamed: 0,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol,company_name,day_date,close_value,volume,open_value,high_value,low_value,return,sent_scores
0,0,550517928399888384,jrs101780,2015-01-01,@davenathan I just expected something more ext...,1,0,0,AAPL,apple,2015-01-01,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 0.643, 'pos': 0.357, 'comp..."
1,1,550518033622368256,bobcatturner,2015-01-01,"Week's Winners and Losers: Apple Gels, Marriot...",0,0,0,AAPL,apple,2015-01-01,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.184, 'neu': 0.649, 'pos': 0.168, 'co..."
2,2,550520264228737024,MilesGeauxbye,2015-01-01,GOOD LUCK“@WSJ: Apple is being sued for falsel...,0,0,0,AAPL,apple,2015-01-01,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 0.805, 'pos': 0.195, 'comp..."
3,3,550521659044552706,bullandbearmash,2015-01-01,"Commented on: ""2015 Will Be Apple's Year: Rais...",0,0,0,AAPL,apple,2015-01-01,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,4,550523990243295232,TCBFx,2015-01-01,The Closing Bell is out! http://paper.li/BonaC...,0,0,1,AAPL,apple,2015-01-01,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4336269,4336269,1212142968037138432,faang_gang,2019-12-31,$GOOGL also flat today,1,0,0,GOOGL,Google Inc,2019-12-31,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4336270,4336270,1212149780471853057,harveyrosenblum,2019-12-31,If this continues then the market will be enti...,0,0,2,GOOGL,Google Inc,2019-12-31,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.114, 'neu': 0.886, 'pos': 0.0, 'comp..."
4336271,4336271,1212150279656890374,luke_sosnowski,2019-12-31,Great day and years end over at #TRICKTRADES m...,1,2,7,GOOGL,Google Inc,2019-12-31,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 0.801, 'pos': 0.199, 'comp..."
4336272,4336272,1212150864066023427,Flower_Power_67,2019-12-31,#FastMoneyEspressoFINAL TRADES:Steve Grasso —>...,0,1,4,GOOGL,Google Inc,2019-12-31,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4336273,4336273,1212157343351238656,naashonomics,2019-12-31,$FB $AMZN $GOOGL $NFLX #FANG 2019,0,0,0,GOOGL,Google Inc,2019-12-31,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."

In [17]:
#I wonder what would happen if we aggregated # reactions (comments, likes, retweets) per post and used that as a feature.
#My hypothesis is that it would have more influence
#also maybe positive and negative per ticker symbol per day has more influence? 
#The closing price and return per is the same across the stock

In [18]:
main_df['compound']  = main_df['sent_scores'].apply(lambda score_dict: score_dict['compound'])

In [24]:
main_df['tweet_sent'] = main_df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')

In [25]:
main_df

,Unnamed: 0,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol,company_name,...,close_value,volume,open_value,high_value,low_value,return,sent_scores,compound,snet_dir,tweet_sent
0,0,550517928399888384,jrs101780,2015-01-01,@davenathan I just expected something more ext...,1,0,0,AAPL,apple,...,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 0.643, 'pos': 0.357, 'comp...",0.7769,pos,pos
1,1,550518033622368256,bobcatturner,2015-01-01,"Week's Winners and Losers: Apple Gels, Marriot...",0,0,0,AAPL,apple,...,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.184, 'neu': 0.649, 'pos': 0.168, 'co...",-0.0772,neg,neg
2,2,550520264228737024,MilesGeauxbye,2015-01-01,GOOD LUCK“@WSJ: Apple is being sued for falsel...,0,0,0,AAPL,apple,...,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 0.805, 'pos': 0.195, 'comp...",0.5622,pos,pos
3,3,550521659044552706,bullandbearmash,2015-01-01,"Commented on: ""2015 Will Be Apple's Year: Rais...",0,0,0,AAPL,apple,...,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos,pos
4,4,550523990243295232,TCBFx,2015-01-01,The Closing Bell is out! http://paper.li/BonaC...,0,0,1,AAPL,apple,...,110.38,41304780,112.82,113.13,110.21,NaN,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos,pos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4336269,4336269,1212142968037138432,faang_gang,2019-12-31,$GOOGL also flat today,1,0,0,GOOGL,Google Inc,...,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos,pos
4336270,4336270,1212149780471853057,harveyrosenblum,2019-12-31,If this continues then the market will be enti...,0,0,2,GOOGL,Google Inc,...,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.114, 'neu': 0.886, 'pos': 0.0, 'comp...",-0.4767,neg,neg
4336271,4336271,1212150279656890374,luke_sosnowski,2019-12-31,Great day and years end over at #TRICKTRADES m...,1,2,7,GOOGL,Google Inc,...,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 0.801, 'pos': 0.199, 'comp...",0.8481,pos,pos
4336272,4336272,1212150864066023427,Flower_Power_67,2019-12-31,#FastMoneyEspressoFINAL TRADES:Steve Grasso —>...,0,1,4,GOOGL,Google Inc,...,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos,pos
4336273,4336273,1212157343351238656,naashonomics,2019-12-31,$FB $AMZN $GOOGL $NFLX #FANG 2019,0,0,0,GOOGL,Google Inc,...,1339.39,976061,1335.79,1340.66,1332.13,-0.000239,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos,pos

In [28]:
main_df['reaction_num'] = main_df['comment_num'] + main_df['retweet_num'] + main_df['like_num']

In [30]:
main_df.reaction_num.max()

1703

In [32]:
test_sent = main_df[main_df.tweet_id == 550520264228737024]

In [34]:
print(test_sent.body)

2    GOOD LUCK“@WSJ: Apple is being sued for falsel...
Name: body, dtype: object

In [35]:
print(test_sent.sent_scores)

2    {'neg': 0.0, 'neu': 0.805, 'pos': 0.195, 'comp...
Name: sent_scores, dtype: object

In [40]:
#probably worth looking into individual breakdown for pos/neg/nuetral.  for example, this one is classified as postive, though is mostly nuetral, 
#and has a negative connotation with apple being sued and some sarcasm.

In [37]:
#also might be worth looking at total interaction, and making the pos/neg based on the average cumulative score per day
#in that case, also add a parmeter for number of tweets that day?

<b>Export Dataset with Sentiment</b>

In [38]:
main_df.to_csv(path+'main_df.csv')